import dedent from "dedent";
import { writeFileSync } from "fs";
import { convert } from "./convert";

// const input = dedent`{a!ae;--description="{perget;name}"}`;
const input =
  '{if;{args;1};==;help;{a!ae;--timestamp;--footer="Username help generated by {user.tag}.";--title="Username";--description="View a user\'s in-game name with a simple command.\n";--field1inline;--field1name="Usage";--field1value="`a!username` views your username.\n`a!username [user]` - Views specified user\'s username. Must be a user mention.\n`a!username set [username]` - sets your in-game name.\n`a!username help` - Displays this message.""};{if;{args;1};==;set;{perset;Username_{user.id};{args;2;true}}{a!ae;--title="Username Set";--color="blue";--description="{user.mention} has set their username to: `{perget;Username_{user.id}}`"};{if;{perget;Username_{user.id;{args;1}}};==;;{a!ae;--title="No Username Found";--color="red";--description="{user.mention;{args;1}} has not set a username."};{a!ae;--title="Username for {user.tag;{args;1}}";--color="blue";--description="{perget;Username_{user.id;{args;1}}}}}}}\n ';
const result = convert(input);
console.log({ input, result });
writeFileSync("output.txt", result.output);
